import React, { useState, useEffect, useMemo } from 'react';
import { motion } from 'framer-motion';
import { FileText, Thermometer, Clock, DollarSign, Calculator, ArrowRight, Upload, Download, Search, RefreshCw, Sun, CloudRain, CloudSnow, Cloud, AlertCircle } from 'lucide-react';
import { ToolType } from '../types';

/* --- DATA & CONFIG --- */
const FILE_FORMATS = ["PDF", "DOCX", "JPG", "PNG", "TXT", "PPTX", "XLSX", "HTML"];

// Extended list of fallback timezones for comprehensive global coverage
const FALLBACK_TIMEZONES = [
  "Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", "Africa/Algiers", "Africa/Cairo", "Africa/Casablanca", "Africa/Johannesburg", "Africa/Lagos", "Africa/Nairobi",
  "America/Anchorage", "America/Argentina/Buenos_Aires", "America/Bogota", "America/Caracas", "America/Chicago", "America/Denver", "America/Detroit", "America/Halifax", "America/Lima", "America/Los_Angeles", "America/Mexico_City", "America/New_York", "America/Phoenix", "America/Santiago", "America/Sao_Paulo", "America/Toronto", "America/Vancouver",
  "Asia/Baghdad", "Asia/Bangkok", "Asia/Beijing", "Asia/Colombo", "Asia/Dhaka", "Asia/Dubai", "Asia/Ho_Chi_Minh", "Asia/Hong_Kong", "Asia/Jakarta", "Asia/Jerusalem", "Asia/Karachi", "Asia/Kathmandu", "Asia/Kolkata", "Asia/Kuala_Lumpur", "Asia/Kuwait", "Asia/Manila", "Asia/Phnom_Penh", "Asia/Riyadh", "Asia/Seoul", "Asia/Shanghai", "Asia/Singapore", "Asia/Taipei", "Asia/Tehran", "Asia/Thimphu", "Asia/Tokyo", "Asia/Vientiane", "Asia/Yangon",
  "Atlantic/Azores", "Atlantic/Cape_Verde", "Australia/Adelaide", "Australia/Brisbane", "Australia/Darwin", "Australia/Hobart", "Australia/Melbourne", "Australia/Perth", "Australia/Sydney",
  "Europe/Amsterdam", "Europe/Athens", "Europe/Belgrade", "Europe/Berlin", "Europe/Brussels", "Europe/Budapest", "Europe/Copenhagen", "Europe/Dublin", "Europe/Helsinki", "Europe/Istanbul", "Europe/Kiev", "Europe/Lisbon", "Europe/London", "Europe/Madrid", "Europe/Moscow", "Europe/Oslo", "Europe/Paris", "Europe/Prague", "Europe/Rome", "Europe/Stockholm", "Europe/Vienna", "Europe/Warsaw", "Europe/Zurich",
  "Pacific/Auckland", "Pacific/Fiji", "Pacific/Guam", "Pacific/Honolulu"
];

// Extensive list of currencies with approximate rates to USD
const CURRENCY_RATES: Record<string, number> = {
  USD: 1, EUR: 0.92, NPR: 133.5, GBP: 0.79, JPY: 150.2, AUD: 1.52, CAD: 1.35, 
  CNY: 7.19, INR: 82.9, SGD: 1.34, AED: 3.67, THB: 35.8, CHF: 0.88, HKD: 7.82,
  SEK: 10.35, NZD: 1.61, KRW: 1330.5, MXN: 17.05, BRL: 4.95, RUB: 92.5,
  ZAR: 18.9, TRY: 30.5, SAR: 3.75, PHP: 56.1, IDR: 15600, MYR: 4.77,
  VND: 24500, ILS: 3.65, PLN: 3.98, TWD: 31.5, EGP: 30.9, PKR: 279.5,
  BDT: 109.5, LKR: 313.0, KWD: 0.31, QAR: 3.64, OMR: 0.38, BHD: 0.38
};

const ALL_CURRENCIES = Object.keys(CURRENCY_RATES).sort();

/* --- COMPONENTS --- */

const Converter = () => {
  const [file, setFile] = useState<File | null>(null);
  const [targetFormat, setTargetFormat] = useState('PDF');
  const [status, setStatus] = useState<'idle' | 'converting' | 'done'>('idle');

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setStatus('idle');
    }
  };

  const downloadFile = () => {
    if (!file) return;
    
    // Create a dummy content for the converted file
    const content = `This is a converted version of ${file.name}.\nTarget Format: ${targetFormat}\n\n(This is a demonstration file generated by the portfolio site)`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    // Remove extension and append new one
    const nameWithoutExt = file.name.substring(0, file.name.lastIndexOf('.')) || file.name;
    a.download = `${nameWithoutExt}_converted.${targetFormat.toLowerCase()}`;
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const convert = () => {
    if (!file) return;
    setStatus('converting');
    setTimeout(() => {
      setStatus('done');
    }, 2000); 
  };

  return (
    <div className="flex flex-col gap-6 h-full justify-center">
      <div className="flex justify-between items-center mb-2">
        <h3 className="text-2xl font-bold text-gold">Universal Doc Converter</h3>
        <span className="text-xs bg-white/10 px-2 py-1 rounded text-gray-400">v2.0.3</span>
      </div>
      
      <div className={`border-2 border-dashed rounded-2xl p-8 text-center transition-all duration-300 ${file ? 'border-nepalRed bg-nepalRed/5' : 'border-gray-600 hover:border-nepalBlue hover:bg-white/5'}`}>
        <input type="file" id="file" className="hidden" onChange={handleFileChange} />
        <label htmlFor="file" className="cursor-pointer flex flex-col items-center gap-4">
          <div className="w-16 h-16 rounded-full bg-white/10 flex items-center justify-center">
             {file ? <FileText size={32} className="text-gold" /> : <Upload size={32} className="text-gray-400" />}
          </div>
          <div>
            <span className="text-lg font-medium text-white block mb-1">{file ? file.name : "Drop file or click to upload"}</span>
            <span className="text-xs text-gray-400">{file ? `${(file.size / 1024).toFixed(2)} KB` : "Supports DOCX, JPG, PNG, PDF..."}</span>
          </div>
        </label>
      </div>

      <div className="flex gap-4 items-end">
        <div className="flex-1">
          <label className="block text-xs text-gray-400 mb-2 uppercase tracking-wide">Convert To</label>
          <select 
            value={targetFormat} 
            onChange={(e) => setTargetFormat(e.target.value)}
            className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-white focus:border-gold outline-none appearance-none"
          >
            {FILE_FORMATS.map(f => <option key={f} value={f}>{f}</option>)}
          </select>
        </div>
        
        {status === 'done' ? (
          <button 
            onClick={downloadFile} 
            className="flex-1 bg-green-600 text-white p-3 rounded-lg font-bold hover:shadow-lg hover:bg-green-500 transition-all flex items-center justify-center gap-2 animate-in fade-in"
          >
            <Download size={20} /> Download File
          </button>
        ) : (
          <button 
            onClick={convert} 
            disabled={!file || status === 'converting'}
            className="flex-1 bg-gradient-to-r from-nepalBlue to-blue-700 text-white p-3 rounded-lg font-bold disabled:opacity-50 hover:shadow-lg hover:shadow-blue-900/50 transition-all flex items-center justify-center gap-2"
          >
            {status === 'converting' ? <RefreshCw className="animate-spin" /> : <RefreshCw />}
            {status === 'converting' ? 'Processing...' : 'Convert'}
          </button>
        )}
      </div>

      {status === 'done' && (
        <div className="bg-green-500/20 border border-green-500/50 p-3 rounded-lg text-center text-green-300 text-sm animate-in fade-in slide-in-from-bottom-2">
          File ready! Click download to save your {targetFormat} file.
        </div>
      )}
    </div>
  );
};

const WorldClock = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentTime, setCurrentTime] = useState(new Date());

  // Get all supported timezones from the browser
  const timeZones = useMemo<string[]>(() => {
    try {
      // @ts-ignore: Property 'supportedValuesOf' does not exist on type 'typeof Intl' in some TS versions
      const supported = (Intl as any).supportedValuesOf('timeZone');
      if (supported && supported.length > 0) return supported;
      return FALLBACK_TIMEZONES;
    } catch (e) {
      return FALLBACK_TIMEZONES;
    }
  }, []);

  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const filteredZones = useMemo(() => {
    const normalizedSearch = searchTerm.toLowerCase().replace(' ', '_');
    
    // Merge browser zones with fallback to ensure comprehensive list if searching
    const allZones = Array.from(new Set([...timeZones, ...FALLBACK_TIMEZONES]));
    
    return allZones.filter((zone) => 
      zone.toLowerCase().includes(normalizedSearch)
    ).slice(0, 50); // Limit results for performance
  }, [timeZones, searchTerm]);

  // Format timezone string for display (e.g., "America/New_York" -> "New York (America)")
  const formatZoneName = (zone: string) => {
    const parts = zone.split('/');
    const city = parts[parts.length - 1].replace(/_/g, ' ');
    const region = parts.length > 1 ? parts[0] : '';
    return { city, region };
  };

  return (
    <div className="flex flex-col gap-4 h-full">
      <h3 className="text-2xl font-bold text-gold mb-2">Global Timekeeper</h3>
      
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
        <input 
          type="text" 
          placeholder="Search City (e.g. Kathmandu, New York)..." 
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full bg-black/40 border border-white/10 rounded-full pl-10 pr-4 py-3 text-white focus:border-gold outline-none placeholder-gray-500"
        />
      </div>

      <div className="flex-1 overflow-y-auto pr-2 space-y-2 max-h-[300px]">
        {filteredZones.length > 0 ? filteredZones.map((zone) => {
          const { city, region } = formatZoneName(zone);
          return (
            <div key={zone} className="flex justify-between items-center bg-white/5 p-4 rounded-xl border border-white/5 hover:bg-white/10 transition-colors">
              <div>
                <span className="block font-bold text-lg">{city}</span>
                <span className="text-xs text-gray-400">{region}</span>
              </div>
              <div className="text-right">
                <span className="block font-mono text-xl text-gold font-bold">
                  {currentTime.toLocaleTimeString('en-US', { timeZone: zone, hour: '2-digit', minute: '2-digit' })}
                </span>
                <span className="text-xs text-gray-400">
                  {currentTime.toLocaleDateString('en-US', { timeZone: zone, weekday: 'short', month: 'short', day: 'numeric' })}
                </span>
              </div>
            </div>
          );
        }) : (
          <div className="text-center text-gray-500 mt-10">
             No matching locations found.<br/>Try searching for a continent or major city.
          </div>
        )}
      </div>
    </div>
  );
};

const CalculatorTool = () => {
  const [display, setDisplay] = useState('0');

  const btn = (v: string) => (
    <button 
      onClick={() => {
        if(v === 'C') setDisplay('0');
        else if(v === '=') { try { setDisplay(eval(display).toString()); } catch { setDisplay('Err'); } }
        else setDisplay(display === '0' ? v : display + v);
      }}
      className={`h-12 rounded-lg font-bold text-xl transition-all active:scale-95
        ${v === '=' ? 'bg-gold text-black col-span-2 shadow-[0_0_15px_rgba(255,215,0,0.4)]' : 
          v === 'C' ? 'bg-nepalRed text-white shadow-[0_0_15px_rgba(220,20,60,0.4)]' : 
          'bg-white/10 hover:bg-white/20 text-white'}`}
    >
      {v}
    </button>
  );

  return (
    <div className="flex flex-col h-full justify-center max-w-xs mx-auto w-full">
      <div className="bg-black/60 p-6 rounded-2xl text-right font-mono text-4xl mb-6 overflow-hidden border border-white/10 shadow-inner text-gold">
        {display}
      </div>
      <div className="grid grid-cols-4 gap-3">
        {['7','8','9','/', '4','5','6','*', '1','2','3','-', 'C','0','+','='].map(k => <React.Fragment key={k}>{btn(k)}</React.Fragment>)}
      </div>
    </div>
  );
};

const CurrencyConverter = () => {
  const [amount, setAmount] = useState(1);
  const [from, setFrom] = useState("USD");
  const [to, setTo] = useState("NPR");

  const fromRate = CURRENCY_RATES[from] || 1;
  const toRate = CURRENCY_RATES[to] || 1;
  // Convert to USD then to Target
  const result = (amount / fromRate * toRate).toFixed(2);

  return (
    <div className="flex flex-col gap-6 h-full justify-center">
      <div className="flex justify-between items-center">
        <h3 className="text-2xl font-bold text-gold">Real-Time Exchange</h3>
        <span className="text-xs text-gray-400 bg-white/5 px-2 py-1 rounded">Simulated Live Data</span>
      </div>
      
      <div className="glass-panel p-6 rounded-2xl space-y-6 border border-white/10 shadow-2xl relative overflow-hidden">
        {/* Subtle background glow */}
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-gold/10 rounded-full blur-3xl pointer-events-none"></div>

        <div>
          <label className="text-xs text-gray-400 mb-1 block uppercase tracking-wider">Amount</label>
          <input 
            type="number" 
            value={amount} 
            onChange={e => setAmount(Number(e.target.value))} 
            className="w-full bg-transparent border-b-2 border-white/20 p-2 text-3xl font-bold text-white focus:border-nepalRed outline-none transition-colors" 
          />
        </div>
        
        <div className="flex items-center gap-4">
           <div className="flex-1 group">
             <label className="text-xs text-gray-500 mb-1 block uppercase tracking-wider group-focus-within:text-gold transition-colors">From</label>
             <select 
               value={from} 
               onChange={e => setFrom(e.target.value)} 
               className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-white appearance-none cursor-pointer outline-none transition-all duration-300 hover:border-nepalBlue hover:shadow-[0_0_15px_rgba(0,56,147,0.3)] focus:border-gold focus:shadow-[0_0_15px_rgba(255,215,0,0.2)]"
             >
               {ALL_CURRENCIES.map(c => <option key={c} value={c}>{c}</option>)}
             </select>
           </div>
           <ArrowRight className="text-gray-400 mt-6" />
           <div className="flex-1 group">
             <label className="text-xs text-gray-500 mb-1 block uppercase tracking-wider group-focus-within:text-gold transition-colors">To</label>
             <select 
               value={to} 
               onChange={e => setTo(e.target.value)} 
               className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-white appearance-none cursor-pointer outline-none transition-all duration-300 hover:border-nepalBlue hover:shadow-[0_0_15px_rgba(0,56,147,0.3)] focus:border-gold focus:shadow-[0_0_15px_rgba(255,215,0,0.2)]"
             >
               {ALL_CURRENCIES.map(c => <option key={c} value={c}>{c}</option>)}
             </select>
           </div>
        </div>

        <div className="bg-white/5 rounded-xl p-6 text-center border border-white/10 relative overflow-hidden group hover:border-gold/30 transition-colors duration-500">
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
          <span className="block text-sm text-gray-400 mb-1 uppercase tracking-widest">Converted Amount</span>
          
          {/* Animated result using Framer Motion */}
          <motion.div 
            key={`${from}-${to}`}
            initial={{ opacity: 0.5, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            <span className="block text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-gold via-yellow-200 to-yellow-500 drop-shadow-sm">
              {result} <span className="text-2xl text-white/50">{to}</span>
            </span>
          </motion.div>
          
          <span className="block text-xs text-gray-500 mt-2 font-mono">
            1 {from} = {(toRate / fromRate).toFixed(4)} {to}
          </span>
        </div>
      </div>
    </div>
  );
};

const WeatherTool = () => {
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [data, setData] = useState<{name: string, temp: number, condition: string, humidity: number, wind: number} | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Initial load
  useEffect(() => {
    fetchWeather('Kathmandu');
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => {
        if(search) setDebouncedSearch(search);
    }, 800);
    return () => clearTimeout(timer);
  }, [search]);

  useEffect(() => {
    if (debouncedSearch) fetchWeather(debouncedSearch);
  }, [debouncedSearch]);

  const fetchWeather = async (city: string) => {
    setLoading(true);
    setError('');
    try {
      // 1. Get Lat/Lon from Open-Meteo Geocoding
      const geoResponse = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);
      const geoData = await geoResponse.json();

      if (!geoData.results || geoData.results.length === 0) {
        throw new Error('City not found');
      }

      const { latitude, longitude, name } = geoData.results[0];

      // 2. Get Weather Data
      const weatherResponse = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m`);
      const weatherData = await weatherResponse.json();

      const { temperature_2m, relative_humidity_2m, weather_code, wind_speed_10m } = weatherData.current;

      setData({
        name: name,
        temp: Math.round(temperature_2m),
        condition: getWeatherCondition(weather_code),
        humidity: relative_humidity_2m,
        wind: wind_speed_10m
      });
    } catch (err) {
      setError('Could not fetch weather. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const getWeatherCondition = (code: number) => {
    // WMO Weather interpretation codes (WW)
    if (code === 0) return 'Clear Sky';
    if (code >= 1 && code <= 3) return 'Partly Cloudy';
    if (code >= 45 && code <= 48) return 'Foggy';
    if (code >= 51 && code <= 67) return 'Rainy';
    if (code >= 71 && code <= 77) return 'Snowy';
    if (code >= 80 && code <= 82) return 'Rain Showers';
    if (code >= 95 && code <= 99) return 'Thunderstorm';
    return 'Cloudy';
  };

  const getIcon = (condition: string) => {
    if (condition === 'Clear Sky') return Sun;
    if (condition === 'Rainy' || condition === 'Rain Showers' || condition === 'Thunderstorm') return CloudRain;
    if (condition === 'Snowy') return CloudSnow;
    return Cloud;
  };

  const Icon = data ? getIcon(data.condition) : Cloud;

  return (
    <div className="flex flex-col h-full gap-6">
       <div className="flex justify-between items-center">
         <h3 className="text-2xl font-bold text-gold">Global Weather</h3>
         <span className="text-[10px] text-gray-500">Powered by Open-Meteo</span>
       </div>
       
       <div className="flex gap-2">
         <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
            <input 
                type="text" 
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Enter City (e.g., Kathmandu, London)"
                className="w-full bg-black/40 border border-white/10 rounded-lg pl-10 pr-4 py-3 text-white focus:border-gold outline-none"
            />
         </div>
       </div>

       <div className="flex-1 flex flex-col items-center justify-center text-center p-6 bg-gradient-to-b from-blue-500/20 to-transparent rounded-2xl border border-white/10 animate-in fade-in duration-500 relative">
          {loading ? (
             <div className="absolute inset-0 flex items-center justify-center bg-black/20 backdrop-blur-sm rounded-2xl z-10">
               <RefreshCw className="animate-spin text-gold w-8 h-8" />
             </div>
          ) : null}

          {error ? (
            <div className="text-red-400 flex flex-col items-center gap-2">
              <AlertCircle size={40} />
              <p>{error}</p>
            </div>
          ) : data ? (
            <>
              <Icon size={80} className="text-white mb-4 animate-pulse" />
              <h2 className="text-6xl font-thin mb-2">{data.temp}°<span className="text-3xl">C</span></h2>
              <p className="text-2xl font-bold text-gold mb-1">{data.name}</p>
              <p className="text-lg text-blue-200">{data.condition}</p>
              
              <div className="mt-8 grid grid-cols-3 gap-4 w-full">
                <div className="bg-black/20 p-2 rounded border border-white/5">
                  <span className="block text-xs text-gray-400">Humidity</span>
                  <span className="font-bold">{data.humidity}%</span>
                </div>
                <div className="bg-black/20 p-2 rounded border border-white/5">
                  <span className="block text-xs text-gray-400">Wind</span>
                  <span className="font-bold">{data.wind} km/h</span>
                </div>
                <div className="bg-black/20 p-2 rounded border border-white/5">
                  <span className="block text-xs text-gray-400">UV</span>
                  <span className="font-bold">Mod</span>
                </div>
              </div>
            </>
          ) : (
            <div className="text-gray-500">Search for a city to see weather data</div>
          )}
       </div>
    </div>
  );
};

/* --- MAIN TOOLS CONTAINER --- */
const Tools: React.FC = () => {
  const [activeTool, setActiveTool] = useState<ToolType>('converter');

  return (
    <div className="flex flex-col md:flex-row gap-6 h-full min-h-[500px]">
      {/* Sidebar */}
      <div className="md:w-64 flex md:flex-col gap-2 overflow-x-auto pb-2 md:pb-0 scrollbar-hide">
        {[
          { id: 'converter', icon: <FileText size={20} />, label: 'Converter', desc: 'PDF, DOCX, IMG' },
          { id: 'clock', icon: <Clock size={20} />, label: 'World Clock', desc: 'Global Zones' },
          { id: 'currency', icon: <DollarSign size={20} />, label: 'Currency', desc: 'Live Rates' },
          { id: 'temperature', icon: <Thermometer size={20} />, label: 'Weather', desc: 'Global Forecast' },
          { id: 'calculator', icon: <Calculator size={20} />, label: 'Calculator', desc: 'Basic Math' },
        ].map((tool) => (
          <button
            key={tool.id}
            onClick={() => setActiveTool(tool.id as ToolType)}
            className={`flex items-center gap-4 px-5 py-4 rounded-xl transition-all whitespace-nowrap text-left group
              ${activeTool === tool.id 
                ? 'bg-gradient-to-r from-nepalRed to-red-800 text-white shadow-lg translate-x-2' 
                : 'bg-white/5 hover:bg-white/10 text-gray-300 hover:translate-x-1'}`}
          >
            <div className={`p-2 rounded-lg ${activeTool === tool.id ? 'bg-white/20' : 'bg-black/20'}`}>
              {tool.icon}
            </div>
            <div>
              <span className="block font-bold">{tool.label}</span>
              <span className={`text-xs block ${activeTool === tool.id ? 'text-white/70' : 'text-gray-500'}`}>{tool.desc}</span>
            </div>
          </button>
        ))}
      </div>

      {/* Content Area */}
      <div className="flex-1 glass-panel rounded-3xl p-8 border border-white/10 shadow-2xl bg-black/40 backdrop-blur-xl relative overflow-hidden">
        {/* Decorative Background Elements */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-nepalBlue/10 rounded-full blur-3xl -z-10 transform translate-x-1/2 -translate-y-1/2"></div>
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-nepalRed/10 rounded-full blur-3xl -z-10 transform -translate-x-1/2 translate-y-1/2"></div>
        
        {activeTool === 'converter' && <Converter />}
        {activeTool === 'clock' && <WorldClock />}
        {activeTool === 'currency' && <CurrencyConverter />}
        {activeTool === 'calculator' && <CalculatorTool />}
        {activeTool === 'temperature' && <WeatherTool />}
      </div>
    </div>
  );
};

export default Tools;